name: Test Run Script

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      version:
        description: "v1.3.0"
        required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  push-image-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Echo Version
        run: echo "v1.7.30" | tr v _
