# This is a basic workflow to help you get started with Actions

name: Test Action

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      version:
        description: "v1.3.0"
        required: false
        
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  push-image-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Echo Version
        run: echo $("${{ github.event.inputs.version }}" -replace 'v','')
